name: Daily Empty Commit
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
    - name: Create Empty Commit
      run: |
        git commit --allow-empty -m "test commit for 1 minute"
    - name: Push Changes
      run: |
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/iamssuraj/Interactive-Lung-Cancer-Detection-System.git
